version: "3.9"
services:
  app:
    build: .
    ports:
     - "8000:80"
    volumes:
        - .:/var/www/html
    working_dir: /var/www/html
    container_name: task-todo
  mysql:
    image: mariadb:10.8.3
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-10-task-list
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080